# -*- coding: utf-8 -*-
"""Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_7w1vAVzzjFaiiG_ipmuPwSPhUwGqFp
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Setup UI
st.set_page_config(page_title="Bike Sharing Dashboard 🚲", layout="wide")

# Load Data
def load_data():
    # Mengambil data dari folder yang sama
    df_day = pd.read_csv("dashboard/main_data.csv")
    df_hour = pd.read_csv("dashboard/main_data_hour.csv")
    df_day['dteday'] = pd.to_datetime(df_day['dteday'])
    return df_day, df_hour

day_df, hour_df = load_data()

# Mapping manual di dalam dashboard agar tidak NaN
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
day_df['season'] = day_df['season'].map(season_map)

# --- SIDEBAR ---
with st.sidebar:
    st.title("Desca's Bike Dashboard")
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

    start_date, end_date = st.date_input(
        label='Rentang Waktu',
        min_value=day_df["dteday"].min(),
        max_value=day_df["dteday"].max(),
        value=[day_df["dteday"].min(), day_df["dteday"].max()]
    )

# Filter
main_df = day_df[(day_df["dteday"] >= pd.to_datetime(start_date)) &
                 (day_df["dteday"] <= pd.to_datetime(end_date))]

# --- DISPLAY ---
st.title("Bike Sharing Analysis 🚲")

col1, col2 = st.columns(2)
with col1:
    st.metric("Total Rentals", value=main_df.cnt.sum())
with col2:
    st.metric("Average Humidity", value=f"{round(main_df.hum.mean(), 2)}%")

st.subheader("Tren Penyewaan 2011 vs 2012")
fig, ax = plt.subplots(figsize=(12, 5))
sns.lineplot(data=main_df, x='mnth', y='cnt', hue='yr', marker='o', ax=ax)
st.pyplot(fig)

st.caption("Copyright (c) Desca Affajry Rais 2026")

