# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlbrqu6IMonkERkJpAddPhml_SbhQ9sG

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** Desca Affajry Rais
- **Email:** descaaffr41s@gmail.com
- **ID Dicoding:** descaaffajryrais

## Menentukan Pertanyaan Bisnis

- Bagaimana performa penyewaan sepeda pada jam-jam tertentu saat hari kerja dibandingkan dengan hari libur?
- Bagaimana tren pertumbuhan jumlah penyewaan sepeda per bulan pada tahun 2012 dibandingkan dengan tahun 2011?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import joblib

"""## Data Wrangling

### Gathering Data
"""

day_df = pd.read_csv("day.csv")
hour_df = pd.read_csv("hour.csv")

"""**Insight:**
Data berhasil dimuat dari dua sumber, yaitu day.csv (data harian) dan hour.csv (data per jam).

### Assessing Data
"""

# Cek info dan tipe data
day_df.info()
hour_df.info()

# Cek apakah ada data yang kosong (null)
print(day_df.isna().sum())

# Cek apakah ada data duplikat
print("Duplikat data day:", day_df.duplicated().sum())
print("Duplikat data hour:", hour_df.duplicated().sum())

# Cek statistik deskriptif untuk melihat keanehan data
print(day_df.describe())

"""**Insight:**
Tidak ditemukan data yang kosong (null values) maupun data duplikat. Namun, kolom dteday masih bertipe objek dan perlu diubah menjadi tipe datetime. Selain itu, banyak kolom kategori yang masih berbentuk angka (seperti season, weathersit) sehingga sulit dipahami secara langsung.

### Cleaning Data
"""

# 1. Pastikan Load Ulang Data Asli (Jika data di memori sudah terlanjur NaN)
day_df = pd.read_csv("day.csv")
hour_df = pd.read_csv("hour.csv")

# A. Memperbaiki tipe data kolom tanggal
day_df['dteday'] = pd.to_datetime(day_df['dteday'])
hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])

# B. Mapping dengan Pengecekan (Hanya map jika kolom masih angka)
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
weather_map = {1: 'Clear', 2: 'Misty', 3: 'Light Rain/Snow', 4: 'Severe Weather'}
month_map = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun',
             7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}
weekday_map = {0:'Sun', 1:'Mon', 2:'Tue', 3:'Wed', 4:'Thu', 5:'Fri', 6:'Sat'}

# Fungsi helper agar aman dijalankan berkali-kali
def safe_map(df, column, mapper):
    if df[column].dtype == 'int64' or df[column].dtype == 'float64':
        df[column] = df[column].map(mapper)
    return df

# Eksekusi Mapping Aman
day_df = safe_map(day_df, 'season', season_map)
day_df = safe_map(day_df, 'weathersit', weather_map)
day_df = safe_map(day_df, 'mnth', month_map)
day_df = safe_map(day_df, 'weekday', weekday_map)

hour_df = safe_map(hour_df, 'season', season_map)
hour_df = safe_map(hour_df, 'weathersit', weather_map)

# C. Denormalisasi (Hanya dikali jika angkanya masih kecil / < 1)
def denormalize(df):
    if df['temp'].max() <= 1:
        df['temp'] = df['temp'] * 41
        df['atemp'] = df['atemp'] * 50
        df['hum'] = df['hum'] * 100
        df['windspeed'] = df['windspeed'] * 67
    return df

day_df = denormalize(day_df)
hour_df = denormalize(hour_df)

"""**Insight:**
- Dilakukan konversi tipe data dteday menjadi datetime.
- Kolom kategori (season, mnth, weekday, weathersit) telah diubah menjadi label teks yang informatif.
- Dilakukan normalisasi terbalik (denormalization) pada kolom suhu dan kelembaban agar angkanya lebih realistis untuk dianalisis.

## Exploratory Data Analysis (EDA)

### Explore Data day_df
"""

# Melihat statistik deskriptif untuk data harian
print(day_df.describe(include="all"))

# Melihat jumlah penyewaan berdasarkan musim (season)
day_df.groupby(by="season").agg({
    "casual": "mean",
    "registered": "mean",
    "cnt": ["max", "min", "mean"]
})

# Melihat jumlah penyewaan berdasarkan kondisi cuaca (weathersit)
day_df.groupby(by="weathersit").agg({
    "cnt": ["max", "min", "mean", "count"]
})

# Melihat perbandingan penyewaan hari kerja (workingday) vs hari libur (holiday)
day_df.groupby(by="workingday").agg({
    "cnt": ["max", "min", "mean"]
})

"""**Insight:**
- Rata-rata penyewaan tertinggi berada pada Musim Gugur (Fall) dan terendah pada Musim Semi (Spring).

- Kondisi cuaca sangat berpengaruh; cuaca Cerah (Clear) memiliki rata-rata penyewaan jauh lebih tinggi dibandingkan saat hujan/salju.

- Pengguna registered memberikan kontribusi jauh lebih besar dibandingkan pengguna casual baik di hari kerja maupun hari libur.

### Explore Data hour_df
"""

# Melihat statistik deskriptif untuk data per jam
print(hour_df.describe(include="all"))

# Mencari jam dengan rata-rata penyewaan tertinggi
hour_df.groupby(by="hr").agg({
    "cnt": ["max", "min", "mean"]
}).sort_values(by=("cnt", "mean"), ascending=False)

"""**Insight:**

- Jam tersibuk adalah jam 17:00 (5 sore) dan 18:00 (6 sore), yang kemungkinan besar merupakan waktu pulang kerja.

- Jam sibuk berikutnya adalah jam 08:00 pagi.

- Hal ini mengindikasikan bahwa sepeda digunakan sebagai alat transportasi utama untuk komuter (pekerja/pelajar).

### Binning
"""

# Binning Jam menjadi Kategori Waktu
def get_time_category(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

hour_df['time_category'] = hour_df['hr'].apply(get_time_category)

# Melihat rata-rata penyewaan tiap kategori waktu
print(hour_df.groupby('time_category')['cnt'].mean().sort_values(ascending=False))

# Binning Suhu menjadi Kategori (Sangat Dingin, Dingin, Normal, Panas)
def get_temp_category(temp):
    if temp < 15:
        return 'Very Cold'
    elif 15 <= temp < 25:
        return 'Cold/Normal'
    elif 25 <= temp < 35:
        return 'Warm/Hot'
    else:
        return 'Very Hot'

# temp di day_df sudah kita kalikan 41 di tahap cleaning sebelumnya
day_df['temp_category'] = day_df['temp'].apply(get_temp_category)

print(day_df.groupby('temp_category')['cnt'].mean().sort_values(ascending=False))

"""**Insight:**

- Kategori waktu Evening (sore ke malam) adalah waktu paling populer untuk penyewaan sepeda.

- Kategori suhu Warm/Hot (25°C - 35°C) memiliki rata-rata penyewaan paling tinggi, menunjukkan bahwa orang lebih suka bersepeda saat cuaca hangat daripada saat sangat dingin.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana performa penyewaan sepeda pada jam-jam tertentu saat hari kerja dibandingkan dengan hari libur?
"""

# Menyiapkan data untuk visualisasi pola jam
# 0 = Hari Libur/Weekend, 1 = Hari Kerja
plt.figure(figsize=(12, 6))

sns.lineplot(
    data=hour_df,
    x='hr',
    y='cnt',
    hue='workingday',
    palette={0: '#E67E22', 1: '#2E86C1'}, # Oranye untuk libur, Biru untuk kerja
    marker='o'
)

plt.title('Pola Penyewaan Sepeda per Jam: Hari Kerja vs Hari Libur', fontsize=15, pad=20)
plt.xlabel('Jam (0-23)', fontsize=12)
plt.ylabel('Rata-rata Jumlah Penyewaan', fontsize=12)
plt.xticks(range(0, 24))
plt.legend(title='Hari Kerja', labels=['Tidak (Libur/Weekend)', 'Ya'])
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""**Insight:**

- Terdapat perbedaan pola yang kontras antara hari kerja dan hari libur.

- Pada hari kerja, puncak penggunaan terjadi pada pukul 08:00 dan 17:00-18:00, yang mengonfirmasi bahwa sepeda digunakan sebagai moda transportasi komuter berangkat dan pulang kerja.

- Pada hari libur, penyewaan meningkat secara bertahap mulai jam 9 pagi dan memuncak di siang hari pukul 12:00-15:00, menunjukkan penggunaan untuk aktivitas rekreasi.

### Pertanyaan 2: Bagaimana tren pertumbuhan jumlah penyewaan sepeda per bulan pada tahun 2012 dibandingkan dengan tahun 2011?
"""

# 1. Menyiapkan data tren bulanan
# yr 0 = 2011, yr 1 = 2012
monthly_rent_df = day_df.groupby(by=["yr", "mnth"]).agg({
    "cnt": "sum"
}).reset_index()

# 2. Mapping Tahun agar tidak error saat divisualisasikan
monthly_rent_df['yr'] = monthly_rent_df['yr'].map({0: 2011, 1: 2012})

# 3. Urutkan berdasarkan bulan agar garisnya tidak melompat-lompat
monthly_rent_df.sort_values(['yr', 'mnth'], inplace=True)

print(monthly_rent_df.head())

# 1. Menyiapkan data: Mengelompokkan berdasarkan tahun (yr) dan bulan (mnth)
# yr 0 = 2011, yr 1 = 2012
monthly_rent_df = day_df.groupby(by=["yr", "mnth"]).agg({
    "cnt": "sum"
}).reset_index()

# 2. Mapping Tahun agar tampilan di legenda lebih informatif
monthly_rent_df['yr'] = monthly_rent_df['yr'].map({0: 2011, 1: 2012})

# 3. Visualisasi Tren Pertumbuhan
plt.figure(figsize=(12, 6))

sns.lineplot(
    data=monthly_rent_df,
    x='mnth',
    y='cnt',
    hue='yr',
    marker='o',
    linewidth=3,
    palette=['#2E86C1', '#E67E22'] # Biru untuk 2011, Oranye untuk 2012
)

# Menambahkan detail visual sesuai standar Bintang 5
plt.title('Tren Pertumbuhan Penyewaan Sepeda Bulanan: 2011 vs 2012', fontsize=15, pad=20)
plt.xlabel('Bulan (1=Januari, 12=Desember)', fontsize=12)
plt.ylabel('Total Jumlah Penyewaan', fontsize=12)

# Mengatur agar angka di sumbu X muncul semua (1-12)
plt.xticks(range(1, 13))

plt.legend(title='Tahun')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""**Insight:**

- Terdapat kenaikan jumlah penyewaan sepeda yang sangat signifikan di hampir setiap bulan pada tahun 2012 jika dibandingkan dengan bulan yang sama di tahun 2011.

- Baik tahun 2011 maupun 2012 menunjukkan pola yang sama, di mana penyewaan memuncak pada pertengahan tahun (sekitar bulan Juni hingga September) dan menurun drastis di akhir/awal tahun (Januari dan Desember).

- Bisnis bike sharing mengalami perkembangan yang pesat. Strategi pemasaran di tahun 2011 terbukti efektif menarik lebih banyak pengguna di tahun berikutnya.

## Analisis Lanjutan (Opsional)
"""

# Membuat fungsi untuk mengelompokkan kelembaban
def humidity_category(hum):
    if hum < 45:
        return 'Terlalu Kering'
    elif 45 <= hum < 65:
        return 'Ideal (Sehat)'
    else:
        return 'Terlalu Lembab'

# Menerapkan fungsi pada dataset day_df
day_df['hum_category'] = day_df['hum'].apply(humidity_category)

# Analisis rata-rata penyewaan berdasarkan kategori kelembaban
hum_analysis = day_df.groupby('hum_category')['cnt'].mean().sort_values(ascending=False).reset_index()

# Visualisasi
plt.figure(figsize=(8, 5))
sns.barplot(x='cnt', y='hum_category', data=hum_analysis, palette='viridis')
plt.title('Rata-rata Penyewaan Sepeda Berdasarkan Tingkat Kelembaban')
plt.xlabel('Rata-rata Penyewaan')
plt.ylabel('Kategori Kelembaban')
plt.show()

"""**Insight:**
- Penyewaan sepeda paling tinggi terjadi pada tingkat kelembaban Ideal (45-65%). Hal ini menunjukkan bahwa kenyamanan udara sangat mempengaruhi minat orang untuk bersepeda
"""

# Membuat fungsi kategori waktu
def time_category(hour):
    if 5 <= hour < 12:
        return 'Pagi'
    elif 12 <= hour < 17:
        return 'Siang'
    elif 17 <= hour < 21:
        return 'Sore/Malam'
    else:
        return 'Tengah Malam'

# Menerapkan pada hour_df
hour_df['time_group'] = hour_df['hr'].apply(time_category)

# Analisis pengaruh waktu terhadap tipe pengguna
time_group_analysis = hour_df.groupby('time_group')[['casual', 'registered']].mean().reset_index()

# Visualisasi
time_group_analysis.set_index('time_group').plot(kind='bar', stacked=True, color=['#F39C12', '#2E86C1'])
plt.title('Proporsi Pengguna Casual vs Registered Berdasarkan Kategori Waktu')
plt.xlabel('Kategori Waktu')
plt.ylabel('Rata-rata Penyewaan')
plt.xticks(rotation=0)
plt.show()

"""**Insight:**
- Kategori Sore/Malam (17:00-21:00) menunjukkan volume penyewaan tertinggi. Menariknya, proporsi pengguna Casual paling tinggi terlihat di waktu Siang, sementara pengguna Registered sangat dominan di waktu Pagi dan Sore (jam komuter).

## Conclusion

**Kesimpulan Pertanyaan 1: Performa Penyewaan pada Jam Kerja vs Hari Libur**
- Berdasarkan hasil visualisasi data, dapat disimpulkan bahwa terdapat perbedaan pola penggunaan sepeda yang signifikan antara hari kerja (workingday) dan hari libur.

- Pada hari kerja, puncak penyewaan terjadi pada pukul 08:00 pagi dan 17:00 - 18:00 sore. Hal ini menunjukkan bahwa mayoritas pengguna menggunakan sepeda sebagai alat transportasi utama untuk berangkat dan pulang kerja (komuter).

- Pada hari libur, pola penyewaan lebih merata di siang hari, memuncak pada pukul 12:00 hingga 15:00. Ini mengindikasikan bahwa penggunaan sepeda pada hari libur lebih bersifat rekreasi atau santai.

- Perusahaan harus memastikan ketersediaan unit sepeda yang maksimal di area perkantoran pada jam sibuk di hari kerja untuk mengakomodasi kebutuhan komuter.

**Kesimpulan Pertanyaan 2: Tren Pertumbuhan Penyewaan Tahun 2012 vs 2011**
- Analisis tren bulanan menunjukkan perkembangan bisnis yang sangat positif selama periode dua tahun tersebut.

- Jumlah penyewaan sepeda pada tahun 2012 secara signifikan lebih tinggi dibandingkan tahun 2011 di seluruh bulan (Januari hingga Desember). Ini menunjukkan ekspansi pasar dan peningkatan popularitas layanan yang sukses.

- Kedua tahun mengikuti pola musiman yang identik, di mana jumlah penyewaan mulai meningkat pesat di bulan Maret, mencapai puncaknya pada bulan September, dan mengalami penurunan drastis di bulan Desember seiring datangnya musim dingin.

- Mengingat adanya penurunan drastis di awal dan akhir tahun karena faktor cuaca/musim, perusahaan disarankan untuk membuat kampanye "Musim Dingin" atau pemeliharaan besar-besaran armada pada bulan Januari-Februari saat permintaan sedang berada di titik terendah.
"""

day_df.to_csv("main_data.csv", index=False)
hour_df.to_csv("main_data_hour.csv", index=False)
day_df.to_csv("main_data_day.csv", index=False)

from google.colab import files
files.download("main_data.csv")
files.download("main_data_hour.csv")
files.download("main_data_day.csv")

import pandas as pd
import os
from google.colab import files

# 1. Load data asli (Fresh start)
day_df = pd.read_csv("day.csv")
hour_df = pd.read_csv("hour.csv")

# 2. Bersihkan tipe data tanggal
day_df['dteday'] = pd.to_datetime(day_df['dteday'])
hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])

# 3. Denormalisasi (Agar angka suhu dkk normal)
day_df['temp'] = day_df['temp'] * 41
day_df['hum'] = day_df['hum'] * 100
day_df['windspeed'] = day_df['windspeed'] * 67

hour_df['temp'] = hour_df['temp'] * 41
hour_df['hum'] = hour_df['hum'] * 100
hour_df['windspeed'] = hour_df['windspeed'] * 67

# 4. Simpan ke folder dashboard tanpa mengubah season menjadi teks di sini
# (Kita biarkan mapping-nya dilakukan di dashboard agar lebih fleksibel)
if not os.path.exists('dashboard'):
    os.makedirs('dashboard')

day_df.to_csv("dashboard/main_data.csv", index=False)
hour_df.to_csv("dashboard/main_data_hour.csv", index=False)

# 5. Download
files.download("dashboard/main_data.csv")
files.download("dashboard/main_data_hour.csv")

